services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./data:/docker-entrypoint-initdb.d  # Mount local 'data' folder
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/workspace
    ports:
      - 8080:8080

volumes:
  app-db-data:
