services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./data:/docker-entrypoint-initdb.d  # Mount local 'data' folder
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/workspace
      - .env:/workspace/.env
    ports:
      - 8080:8080

  tests:
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - db
    volumes:
      - .env:/workspace/.env
    command: ["pytest", "tests/", "--cov=app", "--cov-report=term-missing"]

volumes:
  app-db-data: # This volume is defined to store data for your PostgreSQL service persistently, ensuring it isn't lost between container restarts.

# TODO: Data Mounts: You also have a data folder mounted to /docker-entrypoint-initdb.d in your PostgreSQL container, ensuring any SQL scripts in that folder are run on database initialization.
